export const CATEGORY_KEYWORDS = {
  Books: [
    "boek",
    "literatuur",
    "roman",
    "thriller",
    "fantasy",
    "young adult",
    "kook",
    "reis",
    "kunst",
    "psychologie",
    "management",
    "nederlands",
    "engels",
    "duits",
    "frans",
    "spaans",
    "ebook",
    "kobo",
    "magazine",
    "school",
    "studie",
  ],
  Music: [
    "muziek",
    "cd",
    "lp",
    "album",
    "audio",
    "hifi",
    "speaker",
    "koptelefoon",
    "bluetooth",
    "soundbar",
  ],
  Movies: [
    "film",
    "dvd",
    "blu-ray",
    "tv-series",
    "documentaire",
    "cinema",
    "tv",
  ],
  Games: [
    "game",
    "playstation",
    "xbox",
    "nintendo",
    "pc gaming",
    "console",
    "virtual reality",
    "fanshop",
    "gameconsole-accessoires",
  ],
  Technology: [
    "computer",
    "laptop",
    "desktop",
    "telefoon",
    "smartphone",
    "tablet",
    "monitor",
    "televisie",
    "camera",
    "software",
    "netwerk",
    "internet",
    "accessoire",
    "domotica",
    "gps",
    "e-reader",
    "drone",
    "pc-accessoires",
  ],
  "Kids & Toys": [
    "speelgoed",
    "baby",
    "peuter",
    "kind",
    "puzzel",
    "spel",
    "lego",
    "playmobil",
    "pop",
    "knuffel",
    "bouwen",
    "educatief",
    "creatief",
    "verkleed",
    "buiten",
    "trampoline",
    "loopfiets",
    "fidget",
    "spinner",
  ],
  "Beauty & Care": [
    "cosmetica",
    "parfum",
    "verzorging",
    "gezondheid",
    "make-up",
    "scheren",
    "haar",
    "mooi",
    "luxe",
    "elektrische tandenborstel",
  ],
  Sports: [
    "sport",
    "fitness",
    "yoga",
    "voetbal",
    "zwemmen",
    "outdoor",
    "fiets",
    "kamperen",
    "koffer",
    "rugzak",
  ],
  "Home & Living": [
    "wonen",
    "keuken",
    "tuin",
    "huishouden",
    "zetel",
    "tafel",
    "stoel",
    "bed",
    "pot",
    "pan",
    "servies",
    "barbecue",
    "gereedschap",
    "klus",
    "textiel",
    "handwerken",
    "deco",
  ],
  Fashion: ["kleding", "juwelen", "horloge", "tas", "zonnebril", "mode"],
  Office: ["kantoor", "papier", "schrijf", "agenda", "kalender", "bureau"],
  Pets: ["hond", "kat", "paard", "dier", "voer", "ruiter"],
  "Food & Drinks": [
    "voeding",
    "drank",
    "koffie",
    "thee",
    "wijn",
    "bier",
    "snoep",
    "chocolade",
    "bakken",
    "eten",
    "restaurant",
    "supermarkt",
    "biologisch",
    "glutenvrij",
    "vegetarisch",
    "vegan",
  ],
  Electronics: [
    "elektronica",
    "gadget",
    "batterij",
    "oplader",
    "kabel",
    "adapter",
    "smart",
    "wifi",
    "bluetooth",
    "usb",
    "hdmi",
    "led",
    "oled",
    "4k",
    "streaming",
  ],
  Automotive: [
    "auto",
    "motor",
    "fiets",
    "scooter",
    "onderdelen",
    "navigatie",
    "dashcam",
    "auto-onderdelen",
    "motorfiets",
    "elektrische fiets",
    "ebike",
    "helm",
    "brandstof",
    "olie",
  ],
  Education: [
    "onderwijs",
    "cursus",
    "training",
    "certificaat",
    "diploma",
    "universiteit",
    "school",
    "studie",
    "examen",
    "leren",
    "taal",
    "wiskunde",
    "wetenschap",
    "geschiedenis",
    "programmeren",
  ],
  Health: [
    "gezondheid",
    "medisch",
    "apotheek",
    "vitamines",
    "supplementen",
    "therapie",
    "revalidatie",
    "ziekenhuis",
    "arts",
    "tandarts",
    "oogarts",
    "fysiotherapie",
    "massage",
    "wellness",
    "spa",
  ],
  Travel: [
    "reis",
    "vakantie",
    "hotel",
    "vlucht",
    "backpack",
    "koffer",
    "camping",
    "wandelen",
    "reisbeker",
    "paspoort",
    "visa",
    "reisgids",
    "kaart",
    "navigatie",
    "uitstapje",
  ],
} as const;

export const SEARCH_MAPPINGS = {
  // Books & Literature
  books: ["boek", "literatuur", "roman", "thriller", "fantasy", "young adult"],
  book: ["boek", "literatuur", "roman"],
  literature: ["literatuur", "roman"],

  // Entertainment
  music: ["muziek", "cd", "lp", "album"],
  games: ["game", "playstation", "xbox", "nintendo", "console"],
  movies: ["film", "dvd", "blu-ray", "tv-series", "documentaire"],

  // Technology
  tech: ["computer", "laptop", "telefoon", "smartphone", "tablet"],
  technology: [
    "computer",
    "laptop",
    "telefoon",
    "smartphone",
    "tablet",
    "monitor",
  ],
  computer: ["computer", "laptop", "desktop"],
  phone: ["telefoon", "smartphone"],

  // Lifestyle
  toys: ["speelgoed", "baby", "peuter", "kind", "puzzel", "spel"],
  beauty: ["cosmetica", "parfum", "verzorging", "make-up", "scheren"],
  fashion: ["kleding", "mode", "juwelen", "horloge"],
  home: ["wonen", "keuken", "tuin", "huishouden"],
  kids: ["kind", "baby", "peuter", "speelgoed"],
  office: ["kantoor", "bureau", "schrijf"],

  // Health & Family
  health: ["gezondheid", "gezin", "verzorging", "care", "medisch", "vitamines"],
  family: ["gezin", "gezondheid", "baby", "kind"],

  // Sports
  sports: ["sport", "fitness", "yoga", "voetbal", "zwemmen"],
  fitness: ["sport", "fitness", "yoga"],

  // Pets
  pets: ["hond", "kat", "paard", "dier"],
  pet: ["hond", "kat", "paard", "dier"],

  // New search mappings
  food: ["voeding", "eten", "drank", "koffie", "thee", "restaurant"],
  drink: ["drank", "koffie", "thee", "wijn", "bier"],
  electronics: ["elektronica", "gadget", "smart", "wifi", "bluetooth"],
  car: ["auto", "motor", "fiets", "scooter"],
  automotive: ["auto", "motor", "fiets", "scooter", "onderdelen"],
  education: ["onderwijs", "school", "studie", "cursus", "training"],
  travel: ["reis", "vakantie", "hotel", "koffer", "camping"],
} as const;

export function getCategoryKeywords(
  category: keyof typeof CATEGORY_KEYWORDS
): readonly string[] {
  return CATEGORY_KEYWORDS[category];
}

export function getAvailableCategories(): string[] {
  return Object.keys(CATEGORY_KEYWORDS);
}

export function getSearchMappings(): typeof SEARCH_MAPPINGS {
  return SEARCH_MAPPINGS;
}
